### ISSUE TITLE
DaxFormatter doesn’t have a strong name

### ISSUE THREAD

**Issue by gdeckler** [sql-bi/DaxFormatter#11]
Attempting to use DaxFormatter from a signed project results in an error:
System.IO.FileLoadException: 'Could not load file or assembly 'Dax.Formatter, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)'

**Comment by albertospelta** [comment]
Hi @gdeckler, strongly-named assembly added [v.1.1.0](https://github.com/sql-bi/DaxFormatter/releases/tag/v1.1.0)
