### ISSUE TITLE
ServerType enum?

### ISSUE THREAD

**Issue by otykier** [sql-bi/DaxFormatter#13]
https://github.com/sql-bi/DaxFormatter/blob/master/src/Dax.Formatter/AnalysisServices/ServerType.cs

Would it make sense to add the following types?

```csharp
[EnumMember(Value = "AzureAS")]
AzureAnalysisServices,

[EnumMember(Value = "PBI Service")]
PowerBIService,

[EnumMember(Value = "Offline")]
Offline
```

**Comment by marcosqlbi** [comment]
Added to 1.1.1
