### ISSUE TITLE
Spacing options enhancement

### ISSUE THREAD

**Issue by lukasheinz92** [sql-bi/DaxFormatter#8]
Hello, it would be great to add another spacing option to remove spaces after opening bracket and before closing bracket. So instead of ```CALCULATE( [Sales Amount] )``` it would be ```CALCULATE([Sales Amount])``` etc.

**Comment by marcosqlbi** [comment]
We only support features provided by daxformatter.com.
The choice of keeping the space after/before opening/closing bracket is to make the code more readable.
See https://www.sqlbi.com/articles/rules-for-dax-code-formatting/
